package com.android.virtual.util;

/**
 * 常量
 * @author 德友
 */
public class Consts {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "XHook";
    public static final String TAG = PROJECT + "::";

    // Log
    static final String PREFIX_OF_LOGGER = PROJECT + "::HookCompiler ";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.";
}
